IrshadDev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IrshadDev/src/classes/AccountController.cls
//Commented--//
public without sharing class AccountController {
    public Account account{get; set;}
    public string amountOnPage{get;set;}
    public string quantity{get;set;}
    public AccountController(){
        String recordID = ApexPages.currentPage().getParameters().get('id');
        account = [Select Id, Name, Phone, Site, Type, AccountNumber, Rating, Quantity__c, Percentage__c, Amount__c from Account where Id =: recordID];
    }
    
    public void save(){
        //amount 
        upsert account;
    }
    
}